name: Zip Deploy to Azure Blob Storage
on:
  push:
    branches:
    - master
    paths:
    - 'ShaosilBot/**'
env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: ShaosilBot
  PUBLISH_PATH: ShaosilBot/publish
  PUBLISHED_ZIP_FILE: ShaosilBot.zip
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
      
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
      
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.PUBLISH_PATH }}"
      
    - name: Create Zip
      uses: thedoctor0/zip-release@0.6.2
      with:
        type: "zip"
        directory: "${{ env.PUBLISH_PATH }}"
        filename: "${{ env.PUBLISHED_ZIP_FILE }}"
        
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload Zip
      run:
        az storage blob upload --connection-string "${{ secrets.BLOB_CONNECTION_STRING }}" -f "${{ env.PUBLISH_PATH }}/${{ env.PUBLISHED_ZIP_FILE }}" -c functions-deployments -n "${{ env.PUBLISHED_ZIP_FILE }}" --overwrite
    
    - name: Restart Functions App
      run:
        az functionapp restart -n ShaosilBot -g DiscordRG
