name: Zip Deploy to Azure Blob Storage

on:
  push:
    branches:
    - master
    paths:
    - .github\workflows\*
    - '*.sln'
    - 'ShaosilBot**'

env:
  CONFIGURATION: Release
  WORKING_DIRECTORY: ShaosilBot
  PUBLISH_PATH: ShaosilBot/publish
  PUBLISHED_ZIP_FILE: ShaosilBot.zip

jobs:
  Build-Test-Deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.0.2
      
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}
      
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.PUBLISH_PATH }}"

    - name: Run Unit Tests
      run: dotnet test --no-restore

    - name: Create Zip
      uses: thedoctor0/zip-release@0.6.2
      with:
        type: "zip"
        directory: "${{ env.PUBLISH_PATH }}"
        filename: "${{ env.PUBLISHED_ZIP_FILE }}"
        
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload Zip
      run:
        az storage blob upload --connection-string "${{ secrets.BLOB_CONNECTION_STRING }}" -f "${{ env.PUBLISH_PATH }}/${{ env.PUBLISHED_ZIP_FILE }}" -c functions-deployments -n "${{ env.PUBLISHED_ZIP_FILE }}" --overwrite
    
    - name: Restart Functions App
      run:
        az functionapp restart -n ShaosilBot -g DiscordRG